Now that we have a unified Gradle build target, we have a couple more configuration changes to make. All of these changes
have to do with the URL differences between the separate Grails & Angular apps and our new combined deployment.

By default, static resources in a deployed Grails app are served from the  `/static` base URL. That will conflict with
what our Angular app expects, but fortunately, this is a very simple change.

Edit `server/grails-app/conf/application.yml`:
[source,yml]
.server/grails-app/conf/application.yml
----
include::{sourceDir}/server/grails-app/conf/application.yml[indent=0, tag=grailsResourcesPattern]
----

This simply sets the static resources URL to be set to the root context.

Along similar lines, we need to edit the URL that the Angular app uses to make REST calls against the Grails app.
This can be done within `client/src/environments/environment.prod.ts` in the `client` project. This file is used in the production environment and
sets the `serverUrl` to the root context.

[source,javascript]
.client/src/environments/environment.prod.ts
----
include::{sourceDir}/client/src/environments/environment.prod.ts[indent=0]
----